export const MySkills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Teamwork",
  "immutability",
  "CSS BEM convention",
  "CSS Grid",
  " CSS Flexbox",
  "Styled-Components",
  "React Router",
  "Redux-Saga",
  "Redux(Toolkit)",
  "Create -react-app",
  "Working witch API",
  "GitHub Pull Request & Review",
  "Scrum",
];
export const SkillsIWantToLearn = [
  "React Context",
  "TypeScript",
  "Gatsby",
  "Node.js",
  "JS classes",
  "Unit testing",
];
