export const MySkills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Teamwork",
  "Immutability",
  "CSS BEM convention",
  "CSS Grid",
  "CSS Flexbox",
  "SCSS, SASS",
  "Styled-Components",
  "React Router",
  "Redux-Saga",
  "Redux(Toolkit)",
  "Create-react-app",
  "Working witch API",
  "GitHub Pull Request & Review",
  "Scrum",
];
export const SkillsIWantToLearn = [
  "Redux Thunk",
  "React Context",
  "React Native",
  "TypeScript",
  "Gatsby",
  "Vue.js",
  "Node.js",
  "Unit testing",
];
